### ISSUE TITLE
summary_variables in atl_res_patches unclear in help file

### ISSUE THREAD

**Issue by CBeardsworth** [pratikunterwegs/atlastools#33]
I have not yet looked at the MS again, but I am trying to work out what to give summary_variables and summary_functions without re-reading the MS. I think an example at the bottom of this helpfile would be useful. In general, the description itself may also need a bit more for me to work out what the function is for. I can write this when I figure out how to get it to work. Currently atl_res_patch(clean_data) returns a NULL object...

**Comment by pratikunterwegs** [comment]
This has been expanded in the manuscript, but an example has been added to the function as well.
