### ISSUE TITLE
atlas time needs /1000 before it can be used in res data

### ISSUE THREAD

**Issue by CBeardsworth** [pratikunterwegs/atlastools#34]
Perhaps we can add a warning? I was stuck for quite a while as I hadn't realised that I had time in milliseconds. 

I had thought `wat_get_data` already /1000 to get real unix time in seconds. I wonder if a simple warning that the time is not within a reasonable time period would be useful for the res patch function.

**Comment by pratikunterwegs** [comment]
I agree, but I'm leaving this for someone else to implement, sorry.
