### ISSUE TITLE
Explanation of residence patch in atl_patch_summary

### ISSUE THREAD

**Issue by CBeardsworth** [pratikunterwegs/atlastools#35]
It isn't clear to the user whether the output is all points grouped into a residence patches or whether it is a polygons of residence patches. Make this clearer in MS and help file because just using the term residence patch is not enough. 

Add something like: 
`atl_res_patch` clusters positions into residence patches. The result contains only the data that was classified as a residence patch and removes transit between them.  `atl_patch_summary` can be used to extract all points or extract each patch as a spatial polygon.

**Comment by pratikunterwegs** [comment]
Fixed by #47
