### ISSUE TITLE
Description for lim_spat_indep and lim_time_indep from atl_res_patch are swapped

### ISSUE THREAD

**Issue by CBeardsworth** [pratikunterwegs/atlastools#37]
spatial and time measures are swapped in their descriptions:

`lim_spat_indep`	A numeric value of time in minutes of the time difference between two patches for them to be considered independent.

`lim_time_indep`	A numeric value of distance in metres of the spatial distance between two patches for them to the considered independent.

**Comment by pratikunterwegs** [comment]
Fixed by #47

**Comment by pratikunterwegs** [comment]
Fixed by #47
