### ISSUE TITLE
R version 4.2.0 

### ISSUE THREAD

**Issue by niekkoelewijn** [pratikunterwegs/atlastools#62]
Dear creator,

I just installed the latest version of R, and I received the following error when trying to load atlas tools: 

Warning in install.packages :
  package ‘atlastools’ is not available for this version of R

Will this problem be fixed any time soon?

**Comment by pratikunterwegs** [comment]
Hi, ypu're trying `install.packages("atlastools")` - but the package isn't on CRAN, so you'll need to use `remotes` or `devtools`, and run:

`remotes::install_github("pratikunterwegs/atlastools")`

**Comment by niekkoelewijn** [comment]
Thank you! That worked
